name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.5  # Match your local Terraform version

      - name: Initialize Terraform
        run: |
          cd terraform
          terraform init

      - name: Validate Terraform
        run: |
          cd terraform
          terraform validate

      - name: Apply Terraform Configuration
        run: |
          cd terraform
          terraform apply -auto-approve
