name: Continuous Delivery to Azure

on:
  push:
    branches:
      - main  # Trigger deployment when changes are pushed to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.5  # Ensure consistency with your local Terraform version

      - name: Initialize Terraform
        run: terraform init
        working-directory: terraform

      - name: 'Import Existing Resource Group'
        run: |
          terraform import azurerm_resource_group.rg "/subscriptions/c33c0766-83ef-40fc-b9e9-d51bcc4ffca5/resourceGroups/react-app-rg" || echo "Resource Group already imported or does not exist"

      - name: 'Plan Terraform'
        run: terraform plan

      - name: Apply Terraform Configuration
        run: terraform apply -auto-approve
        working-directory: terraform

      - name: Deploy Web App to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: "react-color-app-12345"  # Update with your actual Azure App Service name
          package: web-app/build.zip

      - name: Verify Deployment
        run: curl -I https://react-color-app-12345.azurewebsites.net || exit 1
