name: Deploy React App to Azure with Terraform

on:
  push:
    branches:
      - main  # Runs the workflow when pushing to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AZURE_WEBAPP_NAME: react-color-app-12345  # Replace with your web app name
      AZURE_RG: react-app-rg  # Azure resource group
      AZURE_LOCATION: centralus  # Adjust region as needed

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7  # Use latest stable version

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Deploy React App to Azure
        run: |
          az webapp deployment source config-zip --resource-group $AZURE_RG --name $AZURE_WEBAPP_NAME --src ./build.zip

      - name: Verify Deployment
        run: |
          curl -Is "https://$AZURE_WEBAPP_NAME.azurewebsites.net" | head -n 1
