name: Azure Web App CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./terraform

      - name: Import Azure Resource Group (If Not Already Imported)
        run: |
          terraform import azurerm_resource_group.rg "/subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/myResourceGroup" || true
        working-directory: ./terraform

      - name: Import Azure Static Web App (If Not Already Imported)
        run: |
          terraform import azurerm_static_web_app.static_app "/subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/myResourceGroup/providers/Microsoft.Web/staticSites/myStaticWebApp" || true
        working-directory: ./terraform

      - name: Import Existing Azure Service Plan (If Not Already Imported)
        run: |
          terraform import azurerm_service_plan.app_service_plan "/subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/myResourceGroup/providers/Microsoft.Web/serverFarms/myAppServicePlan" || true
        working-directory: ./terraform

      - name: Import Existing Azure Linux Web App (If Not Already Imported)
        run: |
          terraform import azurerm_linux_web_app.web_app "/subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/myResourceGroup/providers/Microsoft.Web/sites/myUniqueWebApp1234" || true
        working-directory: ./terraform

      - name: Apply Terraform
        run: terraform apply -auto-approve
        working-directory: ./terraform

      - name: Zip Web Application
        run: zip -r webapp.zip ./web-app

      - name: Deploy Web App to Azure App Service
        run: |
          az webapp deploy --resource-group myResourceGroup --name myUniqueWebApp1234 --src-path webapp.zip
        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
